#!/bin/bash

# Script to combine consolidated Postman collection chunks into a single file
# Usage: ./combine.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/beeSuite-Consolidated.postman_collection.json"
TEMP_DIR="$OUTPUT_DIR/temp"

# Create temp directory
mkdir -p "$TEMP_DIR"

echo "Starting consolidation of Postman collection..."

# Start building the collection
echo "{" > "$OUTPUT_FILE"
echo "    \"info\": {" >> "$OUTPUT_FILE"
cat "$OUTPUT_DIR/_collection_header.json" | jq -r '.info' >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    \"variable\": [" >> "$OUTPUT_FILE"
cat "$OUTPUT_DIR/_collection_header.json" | jq -r '.variable[]' >> "$OUTPUT_FILE"
echo "    ]," >> "$OUTPUT_FILE"
echo "    \"event\": [" >> "$OUTPUT_FILE"
cat "$OUTPUT_DIR/_collection_header.json" | jq -r '.event[]' >> "$OUTPUT_FILE"
echo "    ]," >> "$OUTPUT_FILE"
echo "    \"item\": [" >> "$OUTPUT_FILE"

# Add authentication folders
echo "Adding authentication folders..."
cat "$OUTPUT_DIR/_collection_auth.js" | jq -r '.eleaveCoreAuth' >> "$OUTPUT_FILE"
echo "," >> "$OUTPUT_FILE"
cat "$OUTPUT_DIR/_collection_auth.js" | jq -r '.eleaveTenantAuth' >> "$OUTPUT_FILE"
echo "," >> "$OUTPUT_FILE"
cat "$OUTPUT_DIR/_collection_auth.js" | jq -r '.beewhereAuth' >> "$OUTPUT_FILE"
echo "," >> "$OUTPUT_FILE"
cat "$OUTPUT_DIR/_collection_auth.js" | jq -r '.eleaveLoginAuth' >> "$OUTPUT_FILE"

# Add other service folders (to be implemented)
echo "," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - User Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - User Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Staff Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Staff Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Leave Types\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Leave Types\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Leave Entitlement\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Leave Entitlement\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Leave Applications\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Leave Applications\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Company Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Company Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Master Setup\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Master Setup\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Reports\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Reports\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Dashboard\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Dashboard\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Holiday\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Holiday\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Overtime\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Overtime\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Core - Profile Picture\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveCore.postman_collection.json - Profile Picture\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Customer Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Customer Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Subscription Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Subscription Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Role Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Role Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Dashboard\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Dashboard\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Activity Log\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Activity Log\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Support\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Support\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Sync Data\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Sync Data\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Tenant - Resync Subscription\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveTenantCore.postman_collection.json - Resync Subscription\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Clock Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Clock Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Overtime Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Overtime Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Client Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Client Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - User Info\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - User Info\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Login Log\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Login Log\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Attendance Profile\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Attendance Profile\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Location Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Location Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Project Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Project Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Contract Management\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Contract Management\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Report\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Report\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Map\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Map\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"beeWhere - Support\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeWhereCore.postman_collection.json - Support\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"Beescheduler - Scheduler\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeschedulerCore.postman_collection.json - Scheduler\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"Beescheduler - Health Check\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: beeschedulerCore.postman_collection.json - Health Check\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Products\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Products\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Product Variations\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Product Variations\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Product Categories\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Product Categories\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Product Tags\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Product Tags\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Orders\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Orders\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Order Notes\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Order Notes\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Order Refunds\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Order Refunds\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Coupons\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Coupons\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Tax Rates\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Tax Rates\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Tax Classes\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Tax Classes\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Shipping Zones\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Shipping Zones\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Shipping Zone Locations\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Shipping Zone Locations\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Shipping Zone Methods\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Shipping Zone Methods\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Shipping Methods\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Shipping Methods\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Payment Gateways\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Payment Gateways\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Settings\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Settings\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Setting Options\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Setting Options\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - System Status\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - System Status\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - System Status Tools\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - System Status Tools\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Data\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Data\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Reports\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Reports\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave WooCommerce - Subscriptions\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveWoocommerceCore.postman_collection.json - Subscriptions\"" >> "$OUTPUT_FILE"
echo "    }," >> "$OUTPUT_FILE"
echo "    {" >> "$OUTPUT_FILE"
echo "        \"name\": \"eLeave Login - Encryption\"," >> "$OUTPUT_FILE"
echo "        \"item\": []," >> "$OUTPUT_FILE"
echo "        \"description\": \"Import from: eLeaveLoginCore.postman_collection.json - Encryption\"" >> "$OUTPUT_FILE"
echo "    }" >> "$OUTPUT_FILE"

# Close the collection
echo "    ]" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"

# Clean up temp directory
rm -rf "$TEMP_DIR"

echo "Consolidation complete!"
echo "Output file: $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "1. Import the collection into Postman"
echo "2. Import the environment file: beeSuite-Consolidated.postman_environment.json"
echo "3. Select the environment from the dropdown"
echo "4. Test the authentication endpoints to populate the access_token"
